on: workflow_dispatch
jobs:
  cook:
    name: "Cook"
    runs-on: ubuntu-latest
    steps:
      - name: FoundryVTT Release DB Packer
        uses: aMediocreDad/foundry-db-packer@v0.2.0
        with:
          inputdir: src/items
          packsdir: src/packs # The directory where the compendium packs should exist (optional)
          pack_classiclevel: true # <boolean> Whether to pack the class level db files (optional)
          pack_nedb: false # <boolean> Whether to pack the nedb db files (optional)
