on: workflow_dispatch
jobs:
  cook:
    name: "Cook"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install NPM Deps
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: npm ci
        
      - name: Cache NPM Deps
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: node_modules/
          key: npm-${{ hashFiles('package-lock.json') }}
          
      - name: FoundryVTT Release DB Packer
        uses: aMediocreDad/foundry-db-packer@v0.2.0
        with:
          inputdir: src/items
          packsdir: src/packs # The directory where the compendium packs should exist (optional)
          pack_classiclevel: true # <boolean> Whether to pack the class level db files (optional)
          pack_nedb: false # <boolean> Whether to pack the nedb db files (optional)
